version: '3'

services:
    cron_echo:
        build: ./echo
        volumes:
            - ./log/cron_echo:/tmp/cron_echo
        networks:
            - fluent_test
    fluent_sender:
        build: ./fluentd
        volumes:
            - ./log/cron_echo:/tmp/cron_echo
            - ./fluentd/config:/fluentd/etc
            - ./log/fluentd_sender:/fluentd/log
        networks:
            - fluent_test
networks:
    fluent_test:
        external: true
